name: insurveyor-env
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - insurveyor
  - snakemake
  - bcftools
  - bedtools
  - bwa
  - htslib
  - samtools
  - matplotlib
  - numpy
  - pysam
  - pyyaml
  - pandas
  - scipy
  - seaborn
  - requests
  - biopython
  - mafft
  - fasttree
